### ISSUE TITLE
Error Loading with v0.8.666

### ISSUE THREAD

**Issue by bear-fighter** [niatahl/tahlan-shipworks#1]
Upon booting (Starsector 0.95.1a-RC6) I get the error:

`Fatal: Weapon spec [tahlan_blinker_red] not found!
Check starsector.log for more info`

**Comment by niatahl** [comment]
What did you expect from pulling the project in an unfinished state?

**Comment by bear-fighter** [comment]
Didn't know it was unfinished.  The mod updater told me to update.  Was trying to be helpful..

**Comment by niatahl** [comment]
I've sorted version checker out.
