### ISSUE TITLE
Rosenritter Final Ship Location Error

### ISSUE THREAD

**Issue by JamesTripleQ** [niatahl/tahlan-shipworks#3]
Just a heads up that the name of the constellation where the Traumtänzer is isn't actually displayed.

I believe this is because you used:
`Global.getSector().getMemoryWithoutUpdate().getString("$traum_location")`

Instead of:
`Global.getSector().getMemoryWithoutUpdate().getString("$tahlan_traum_location"")`

A screenshot of what it currently displays:
![image](https://user-images.githubusercontent.com/90627380/209581036-3f619a30-18f9-4c64-9c07-bad4fc247ad7.png)

And what is currently in my save file: 
![image](https://user-images.githubusercontent.com/90627380/209581070-d632b022-e377-430d-9be1-0b04001b1fb2.png)

**Comment by niatahl** [comment]
Ah, that snuck in during refactoring, Fixed.
