### ISSUE TITLE
Faction id persean_league isn't the proper faction_id

### ISSUE THREAD

**Issue by Silver-D** [niatahl/tahlan-shipworks#4]
Hi!  I just started a new game with your mod while testing my personal one, and noticed that the PL rep level to the Legio faction isn't getting set as intended properly. I do not have nor tried Nex, nor any other faction changer/adder mod besides the beautiful ScalarTech, so I am unsure if Nex or anything else handles persean_league, but in the base game the proper id is "persean" (dammit, Alex).

It seems you are using persean_league in these files 

```
mods/tahlan-shipworks/jars/src/org/niatahl/tahlan/world/FactionRelationPlugin.java:        legio.setRelationship("persean_league", -0.6f);
mods/tahlan-shipworks/data/config/exerelinFactionConfig/tahlan_legioinfernalis.json:            "persean_league": -0.40,
mods/tahlan-shipworks/data/config/vayraRaiders/tahlan_legioinfernalis.json:             "persean_league":1.5,
mods/tahlan-shipworks/data/config/vayraBounties/rare_flagships.csv:tahlan_rf_dominator_gh,tahlan_dominator_gh_knight,persean_league,0.1,cruising around in low orbit above Mayasura to show off like a snob in
mods/tahlan-shipworks/data/config/vayraBounties/rare_flagships.csv:tahlan_rf_monitor_gh,tahlan_monitor_gh_knight,persean_league,0.2,escaping planetary authorities in
```
Your work is amazing btw!
And I'm very sorry if I got something wrong and bothere you for no good reason, I only stumbled onto this while testing my own crap.

**Comment by niatahl** [comment]
It's unfortunately inconsistent (faction file is called persean_league for example), so that error keeps slipping in. Will fix.
