### ISSUE TITLE
csv switches file pathing from forward slashes to back slashes halfway through the file.

### ISSUE THREAD

**Issue by alan-cugler** [niatahl/tahlan-shipworks#9]
## problem
CSV file switches all its file path `/` to `\` after the `samaveda` section on this [line](https://github.com/niatahl/tahlan-shipworks/blob/a0ce37114c88a4153535e577ba550cb734c44257/data/lights/tahlan_texture.csv#L814
) in the mod zip. Not sure why its happening as the related file in this repo does not have that happening. 

```java
7143 [Thread-4] INFO  com.fs.graphics.TextureLoader  - Cleaned buffer for texture graphics/tahlan/maps/weapon_normals/tahlan_samaveda_cover_r_normal.png (using cast)
37212 [Thread-4] ERROR com.fs.starfarer.combat.CombatMain  - java.lang.RuntimeException: Error loading [graphics\tahlan\maps\weapon_normals\tahlan_aetnos_hp_base_Normal.png] resource, not found in [{USER REDACTED}/starsector/./mods/tahlan-shipworks-1.2.6,{USER REDACTED}../starfarer.res/res,CLASSPATH]
```

## solution
I did findall and replace operation back to `/` in the `tahlan_tecture.csv` file and the mod loaded fine.

**Comment by niatahl** [comment]
has been fixed for weeks

**Comment by alan-cugler** [comment]
I just pulled it down this morning from your [patreon](https://www.patreon.com/posts/87986235) downlaod where the [zip](https://www.patreon.com/file?h=87986235&i=15449286) file is labeled version `1.2.6`.

Opening up `Tahlan_texture.csv` I can see starting around line 815 in the file the `/` are replaced by `\`.
```CSV
tahlan_samaveda_cover_r,hardpoint,,,material,graphics/tahlan/maps/weapon_glib/tahlan_samaveda_cover_r_material.png
tahlan_samaveda_cover_l,turret,,,material,graphics/tahlan/maps/weapon_glib/tahlan_samaveda_cover_l_material.png
tahlan_samaveda_cover_r,turret,,,material,graphics/tahlan/maps/weapon_glib/tahlan_samaveda_cover_r_material.png
,,,,,
tahlan_aetnos,hardpoint,,,material,graphics\tahlan\maps\weapon_glib\tahlan_aetnos_hp_base_material.png
tahlan_aetnos,hardpointbarrel,,,material,graphics\tahlan\maps\weapon_glib\tahlan_aetnos_hp_recoil_material.png
tahlan_alteria,hardpoint,,,material,graphics\tahlan\maps\weapon_glib\tahlan_alteria_hp_base_material.png
tahlan_alteria,hardpointbarrel,,,material,graphics\tahlan\maps\weapon_glib\tahlan_alteria_hp_recoil_material.png
```

## Hypothesis
Mayeb this has been fixed in the repo for weeks but the zip file currently available on Patreon is older than the latest branch in github?

**Comment by alan-cugler** [comment]
Pulled down the [github](https://github.com/niatahl/tahlan-shipworks/releases) mirror of the [zip](https://github.com/niatahl/tahlan-shipworks/releases/download/1.2.6/tahlan-shipworks-1.2.6.zip) file from version `1.2.6`.

Opening up `Tahlan_texture.csv` I can see starting around line 815 in the file the `/` are replaced by `\`.
```
tahlan_samaveda_cover_r,hardpoint,,,material,graphics/tahlan/maps/weapon_glib/tahlan_samaveda_cover_r_material.png
tahlan_samaveda_cover_l,turret,,,material,graphics/tahlan/maps/weapon_glib/tahlan_samaveda_cover_l_material.png
tahlan_samaveda_cover_r,turret,,,material,graphics/tahlan/maps/weapon_glib/tahlan_samaveda_cover_r_material.png
,,,,,
tahlan_aetnos,hardpoint,,,material,graphics\tahlan\maps\weapon_glib\tahlan_aetnos_hp_base_material.png
tahlan_aetnos,hardpointbarrel,,,material,graphics\tahlan\maps\weapon_glib\tahlan_aetnos_hp_recoil_material.png
tahlan_alteria,hardpoint,,,material,graphics\tahlan\maps\weapon_glib\tahlan_alteria_hp_base_material.png
tahlan_alteria,hardpointbarrel,,,material,graphics\tahlan\maps\weapon_glib\tahlan_alteria_hp_recoil_material.png

```

**Comment by alan-cugler** [comment]
I see, so it was [updated](https://github.com/niatahl/tahlan-shipworks/commit/4ac3073bac23902f6b4ab7d27c44cb1d10734169#diff-f53c653f4c7a0048c8eb5fb9694fae985b273cb56db9e2fa9f6573eb90887f87) three weeks ago, just a new version hasnt been cut to replace `1.2.6` for tahlan-shipworks. Sorry for the non issue, I think I need more coffee lol
